version: '3.8'

services:
  tmc:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    image: hav93/tmc:local
    container_name: tmc-local
    restart: unless-stopped
    ports:
      - "9393:9393"
    volumes:
      # 开发模式：挂载关键代码文件实现热更新
      - ../app/backend/api:/app/api
      - ../app/backend/services:/app/services
      - ../app/backend/alembic:/app/alembic
      - ../app/backend/models.py:/app/models.py
      - ../app/backend/main.py:/app/main.py
      - ../app/backend/enhanced_bot.py:/app/enhanced_bot.py
      - ../app/backend/telegram_client_manager.py:/app/telegram_client_manager.py
      - ../app/backend/docker-entrypoint.sh:/docker-entrypoint.sh
      # 前端热挂载（开发模式）
      - ../app/frontend/dist:/app/frontend/dist
      # 数据目录
      - ../data:/app/data
      - ../sessions:/app/sessions
      - tmc-logs:/app/logs
      # 媒体管理相关目录（v1.3.0 新增）
      - ../media/downloads:/app/media/downloads
      - ../media/storage:/app/media/storage
      # CloudDrive 和外部挂载目录（可选）
      - tmc-mnt:/mnt
    environment:
      # Telegram 客户端配置（完全可选，推荐通过 Web 界面配置）
      - API_ID=${API_ID:-}
      - API_HASH=${API_HASH:-}
      - BOT_TOKEN=${BOT_TOKEN:-}
      - PHONE_NUMBER=${PHONE_NUMBER:-}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=sqlite:////app/data/bot.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1}
    networks:
      - tmc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9393/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  tmc-logs:
    driver: local
  tmc-mnt:
    driver: local

networks:
  tmc-network:
    driver: bridge

